# Generated by Django 4.1.7 on 2023-03-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_img', models.CharField(max_length=128, verbose_name='图片链接')),
                ('goods_title', models.CharField(max_length=128, verbose_name='商品标题')),
                ('goods_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='商品价格')),
                ('goods_sales', models.CharField(max_length=32, verbose_name='商品销量')),
                ('shop_title', models.CharField(max_length=64, verbose_name='店铺名')),
                ('shop_platform', models.CharField(max_length=32, verbose_name='平台')),
                ('goods_link', models.CharField(max_length=128, verbose_name='商品链接')),
                ('grab_time', models.DateTimeField(verbose_name='抓取时间')),
            ],
        ),
    ]
